[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.12"

[features]
seeds = false
skip-lint = false
[programs.localnet]
twitter = "F6NKeaoPbchYnbcJZ5YSAqfMcHuP7GLExTuDK3qmgtgW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
