[package]
name = "task2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
rand = "0.8.5"
float-cmp = "0.10.0"

[profile.test]
overflow-checks = true
